{% set name = "pdftext" %}
{% set version = "0.5.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdftext-{{ version }}.tar.gz
  sha256: 81646068c98df4874064f739f507908543188e93e1a5d84b30a0989329f32af6

build:
  entry_points:
    - pdftext = extract_text:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - click >=8.1.8,<9.0.0
    - onnxruntime >=1.19.2,<2.0.0
    - python >={{ python_min }},<3.13
    - pypdfium2 =4.30.0
    - scikit-learn >=1.4.2,<2.0.0
    - pydantic >=2.7.1,<3.0.0
    - pydantic-settings >=2.2.1,<3.0.0

test:
  imports:
    - pdftext
  commands:
    - pip check
    - pdftext --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/VikParuchuri/pdftext
  summary: Extract structured text from pdfs quickly
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
